import { RecoRecord } from '../types';

export const SAMPLE_RECORDS: RecoRecord[] = [
  {
    id: 'sample-spending',
    createdAt: '2026-09-16T15:20:00.000Z',
    kind: 'spending',
    date: '2026-09-16',
    store: '달밤커피',
    category: '카페',
    address: '서울 마포구 연남동',
    items: [
      { name: '아이스 아메리카노', qty: 2, price: 4500 },
      { name: '바스크 치즈케이크', qty: 1, price: 6500 },
      { name: '드립백 원두', qty: 3, price: 1000 },
    ],
    memo: '☕',
  },
  {
    id: 'sample-movie',
    createdAt: '2026-09-12T10:45:00.000Z',
    kind: 'movie',
    date: '2026-09-12',
    time: '19:30',
    title: '오디세이',
    originalTitle: 'Odyssey',
    theater: 'CGV 강남점',
    screen: '4관',
    seat: 'H11',
    people: 1,
    format: '2D',
    ageRating: '12세이상관람가',
    stars: 5,
    runtime: '156',
  },
  {
    id: 'sample-reading',
    createdAt: '2026-09-09T11:45:10.000Z',
    kind: 'reading',
    date: '2026-09-09',
    title: '오디세이아(고대 그리스어 완역본)',
    author: '호메로스',
    publisher: '현대지성',
    genre: '인문',
    status: '완독',
    place: '교보문고 광화문점',
    memo: '돌아갈 곳이 있다는 건 긴 여정을 버티게 한다.',
  },
];
